## YAML Template.
---
password: password

#Server configuration.
server:
    applicationConnectors:
        - type: http
          port: 8080
          
        - type: https
          port: 8443
          
          keyStorePath: dropbookmarks.keystore
          keyStorePassword: password
          validateCerts: false

# Database settings.
database:

  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: sa

  # the JDBC URL
  url: jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1